#spring:
#  datasource:
#    driver-class-name: "org.h2.Driver"
#    url: "jdbc:h2:mem:dev_db"
#    username: "sa"
#    password: "sa"
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
spring:
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gdstest
    username: joshvince
    password:
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port
